+define+SVT_UVM_TECHNOLOGY   
+define+SYNOPSYS_SV
+libext+.v+.sv+.svh
+define+SVT_UART
+define+UVM 
+define+UVM_NO_DEPRECATED 
+define+UVM_REGEX_NO_DPI 
+define+UVM_REG_ADDR_WIDTH=32 
+define+UVM_REG_DATA_WIDTH=32 
+define+UVM_REG_BYTENABLE_WIDTH=4 
+define+UVM_PACKER_MAX_BYTES=8000 
+incdir+/home/share/pro/OpenTitan/opentitan_gw/hw/ip/uart/dv/uart_vip/src/sverilog/vcs
+incdir+/home/share/pro/OpenTitan/opentitan_gw/hw/ip/uart/dv/uart_vip/include/sverilog 
+incdir+/home/share/pro/OpenTitan/opentitan_gw/hw/ip/uart/dv/uart_vip/src/verilog/vcs
+incdir+/home/share/pro/OpenTitan/opentitan_gw/hw/ip/uart/dv/uart_vip/include/verilog
